"""added mtg user info columns

Revision ID: 02e6704aaf89
Revises: 8b3a2b76c2b3
Create Date: 2026-10-05 14:12:19.763231

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "02e6704aaf89"
down_revision: Union[str, Sequence[str], None] = "8b3a2b76c2b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("guild_configs") as batch_op:
        batch_op.alter_column(
            "update_channel",
            new_column_name="animanga_channel",
            existing_type=sa.Integer(),
            existing_nullable=False,
        )
    op.add_column("users", sa.Column("playgroup_id", sa.Integer(), nullable=True))
    op.add_column(
        "users", sa.Column("playgroup_name", sa.String(length=240), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("guild_configs") as batch_op:
        batch_op.alter_column(
            "animanga_channel",
            new_column_name="update_channel",
            existing_type=sa.Integer(),
            existing_nullable=False,
        )
    op.add_column(
        "guild_configs", sa.Column("update_channel", sa.INTEGER(), nullable=True)
    )
    op.drop_column("guild_configs", "animanga_channel")
    # ### end Alembic commands ###
