"""update_trains_models

Revision ID: 21b348e4408e
Revises: d35e5fda2c90
Create Date: 2026-05-09 23:56:59.054658

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite
from sqlalchemy.exc import OperationalError

# revision identifiers, used by Alembic.
revision: str = "21b348e4408e"
down_revision: Union[str, Sequence[str], None] = "d35e5fda2c90"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.add_column("player_tiles", sa.Column("row", sa.Integer(), nullable=False))
        op.add_column("player_tiles", sa.Column("column", sa.Integer(), nullable=False))
        op.add_column("train_games", sa.Column("date", sa.DateTime(), nullable=False))
        op.add_column(
            "train_games", sa.Column("board_height", sa.Integer(), nullable=False)
        )
        op.drop_column("train_games", "board_length")
        op.drop_column("train_games", "known_entries")
        op.add_column(
            "train_players", sa.Column("start_col", sa.Integer(), nullable=False)
        )
        op.add_column(
            "train_players", sa.Column("start_row", sa.Integer(), nullable=False)
        )
        op.add_column(
            "train_players", sa.Column("end_col", sa.Integer(), nullable=False)
        )
        op.add_column(
            "train_players", sa.Column("end_row", sa.Integer(), nullable=False)
        )
    except OperationalError as e:
        print(f"Skipped operation due to {e}")
    with op.batch_alter_table("train_players", schema=None) as batch_op:
        batch_op.drop_column("start_tile_id")
        batch_op.drop_column("end_tile_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "train_players", sa.Column("end_tile_id", sa.INTEGER(), nullable=True)
    )
    op.add_column(
        "train_players", sa.Column("start_tile_id", sa.INTEGER(), nullable=True)
    )
    op.create_foreign_key(None, "train_players", "train_tiles", ["end_tile_id"], ["id"])
    op.create_foreign_key(
        None, "train_players", "train_tiles", ["start_tile_id"], ["id"]
    )
    op.drop_column("train_players", "end_row")
    op.drop_column("train_players", "end_col")
    op.drop_column("train_players", "start_row")
    op.drop_column("train_players", "start_col")
    op.add_column(
        "train_games", sa.Column("known_entries", sqlite.JSON(), nullable=True)
    )
    op.add_column(
        "train_games", sa.Column("board_length", sa.INTEGER(), nullable=False)
    )
    op.drop_column("train_games", "board_height")
    op.drop_column("train_games", "date")
    op.drop_column("player_tiles", "column")
    op.drop_column("player_tiles", "row")
    op.add_column(
        "bingo_games", sa.Column("known_entries", sqlite.JSON(), nullable=True)
    )
    # ### end Alembic commands ###
