"""add_daily_stat_tracking

Revision ID: 3008451ee01b
Revises: b75e9c9ab3f5
Create Date: 2026-05-10 21:24:37.523050

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3008451ee01b"
down_revision: Union[str, Sequence[str], None] = "b75e9c9ab3f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "animanga_list_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("media_id", sa.Integer(), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("is_manga", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "media_id", name="uq_user_media"),
    )
    op.create_index("ix_user_id", "animanga_list_entries", ["user_id"], unique=False)
    op.create_table(
        "animanga_daily_stats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("minutes_watched", sa.Integer(), nullable=False),
        sa.Column("placement", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("episodes", sa.Integer(), nullable=False),
        sa.Column("movies", sa.Integer(), nullable=False),
        sa.Column("manga_chapters", sa.Integer(), nullable=False),
        sa.Column("ln_chapters", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["guild_id"],
            ["guilds.id"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_dailystats_guild_id", "animanga_daily_stats", ["guild_id"], unique=False
    )
    op.add_column(
        "members",
        sa.Column(
            "stat_tracking_enabled",
            sa.Boolean(),
            server_default=sa.text("0"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("members", "stat_tracking_enabled")
    op.drop_index("ix_dailystats_guild_id", table_name="animanga_daily_stats")
    op.drop_table("animanga_daily_stats")
    op.drop_index("ix_user_id", table_name="animanga_list_entries")
    op.drop_table("animanga_list_entries")
    # ### end Alembic commands ###
