"""rename_emoji_train_item

Revision ID: 3addf2ecec14
Revises: 66c8cc4ef364
Create Date: 2026-05-12 10:18:10.715154

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3addf2ecec14"
down_revision: Union[str, Sequence[str], None] = "66c8cc4ef364"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "train_items", sa.Column("emoji_name", sa.String(length=40), nullable=False)
    )
    op.drop_column("train_items", "emoji")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "train_items", sa.Column("emoji", sa.VARCHAR(length=40), nullable=False)
    )
    op.drop_column("train_items", "emoji_name")
    # ### end Alembic commands ###
