"""train_player_positions

Revision ID: 50482019320b
Revises: 3addf2ecec14
Create Date: 2026-05-13 16:22:31.263605

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "50482019320b"
down_revision: Union[str, Sequence[str], None] = "3addf2ecec14"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "train_players", sa.Column("current_col", sa.Integer(), nullable=True)
    )
    op.add_column(
        "train_players", sa.Column("current_row", sa.Integer(), nullable=True)
    )
    op.add_column(
        "train_players", sa.Column("last_bought_col", sa.Integer(), nullable=True)
    )
    op.add_column(
        "train_players", sa.Column("last_bought_row", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("train_players", "last_bought_row")
    op.drop_column("train_players", "last_bought_col")
    op.drop_column("train_players", "current_row")
    op.drop_column("train_players", "current_col")
    # ### end Alembic commands ###
