"""rename_anilist_media_id

Revision ID: 55a5f7403654
Revises: 8d7f4707df3e
Create Date: 2026-05-06 12:37:28.209924

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "55a5f7403654"
down_revision: Union[str, Sequence[str], None] = "8d7f4707df3e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_bingo_game_guild_id", "bingo_games", ["guild_id"], unique=False)

    op.add_column(
        "bingo_shots",
        sa.Column("anilist_entry_id", sa.Integer(), nullable=True),
    )

    # Copy data
    op.execute("""
        UPDATE bingo_shots
        SET anilist_entry_id = anilist_media_id
    """)

    op.drop_column("bingo_shots", "anilist_media_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bingo_shots", sa.Column("anilist_media_id", sa.INTEGER(), nullable=False)
    )
    op.drop_column("bingo_shots", "anilist_entry_id")
    op.drop_index("ix_bingo_game_guild_id", table_name="bingo_games")
    # ### end Alembic commands ###
