"""response_behavior

Revision ID: 6f034c3fd210
Revises: 803919e5895b
Create Date: 2026-05-11 21:40:50.163515

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6f034c3fd210"
down_revision: Union[str, Sequence[str], None] = "803919e5895b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("responses", sa.Column("behavior", sa.Integer(), nullable=True))
    op.execute("""
        UPDATE responses
        SET behavior = CASE
            WHEN is_exact = 1 THEN 1
            ELSE 0
        END
    """)

    with op.batch_alter_table("responses", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("uq_response_guild_trigger_text_exact"), type_="unique"
        )
        batch_op.create_unique_constraint(
            "uq_response_guild_trigger_text_behavior",
            ["guild_id", "trigger", "text", "behavior"],
        )
    op.drop_column("responses", "is_exact")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    op.add_column("responses", sa.Column("is_exact", sa.BOOLEAN(), nullable=True))

    op.execute("""
        UPDATE responses
        SET is_exact = CASE
            WHEN behavior = 1 THEN 1  -- Exact
            ELSE 0                    -- Phrase (and Correction → treated as non-exact)
        END
    """)

    with op.batch_alter_table("responses") as batch_op:
        batch_op.alter_column("is_exact", nullable=False)

        batch_op.drop_constraint(
            "uq_response_guild_trigger_text_behavior", type_="unique"
        )

        batch_op.create_unique_constraint(
            batch_op.f("uq_response_guild_trigger_text_exact"),
            ["guild_id", "trigger", "text", "is_exact"],
        )

        batch_op.drop_column("behavior")
