"""train_gem_time

Revision ID: 73737f66f78e
Revises: 7739e0a7ac64
Create Date: 2026-05-15 10:59:57.838303

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "73737f66f78e"
down_revision: Union[str, Sequence[str], None] = "7739e0a7ac64"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("train_players", sa.Column("gem_time", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("train_players", "gem_time")
    # ### end Alembic commands ###
