"""shot_anilist_info

Revision ID: 7739e0a7ac64
Revises: cad70a87a04f
Create Date: 2026-05-14 03:35:36.573544

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "7739e0a7ac64"
down_revision: Union[str, Sequence[str], None] = "cad70a87a04f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "train_shots",
        sa.Column("anilist_info", sa.JSON(), nullable=False, server_default="{}"),
    )
    op.drop_column("train_shots", "genres")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("train_shots", sa.Column("genres", sqlite.JSON(), nullable=False))
    op.drop_column("train_shots", "anilist_info")
    # ### end Alembic commands ###
