"""train_start_end_nullable

Revision ID: 7c0e63f701b2
Revises: 7f56b4215f57
Create Date: 2026-05-11 18:00:11.504332

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7c0e63f701b2"
down_revision: Union[str, Sequence[str], None] = "7f56b4215f57"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("train_players", schema=None) as batch_op:
        batch_op.alter_column("start_col", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("start_row", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("end_col", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("end_row", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "train_players", "end_row", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "train_players", "end_col", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "train_players", "start_row", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "train_players", "start_col", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
