"""train_fixes

Revision ID: 7f56b4215f57
Revises: 3008451ee01b
Create Date: 2026-05-11 16:10:02.521332

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7f56b4215f57"
down_revision: Union[str, Sequence[str], None] = "3008451ee01b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("player_tiles", schema=None) as batch_op:
        batch_op.drop_constraint("fk_current_tile_id", type_="foreignkey")
    op.drop_column("train_players", "current_tile_id")
    op.add_column(
        "player_tiles", sa.Column("rail_text", sa.String(length=400), nullable=True)
    )
    op.add_column("train_shots", sa.Column("genres", sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("train_shots", "genres")
    op.add_column(
        "train_players", sa.Column("current_tile_id", sa.INTEGER(), nullable=True)
    )
    op.create_foreign_key(
        None, "train_players", "player_tiles", ["current_tile_id"], ["id"]
    )
    op.drop_column("player_tiles", "rail_text")
    # ### end Alembic commands ###
