"""remove_visible

Revision ID: 803919e5895b
Revises: 7c0e63f701b2
Create Date: 2026-05-11 18:11:03.607042

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "803919e5895b"
down_revision: Union[str, Sequence[str], None] = "7c0e63f701b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("train_player", schema=None) as batch_op:
        batch_op.drop_index("ix_train_player_tile_player_visible")
    try:
        op.drop_column("player_tiles", "visible")
    except Exception as e:
        print(e)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("player_tiles", sa.Column("visible", sa.BOOLEAN(), nullable=False))
    op.create_index(
        op.f("ix_train_player_tile_player_visible"),
        "player_tiles",
        ["player_id", "visible"],
        unique=False,
    )
    # ### end Alembic commands ###
