"""empty message

Revision ID: 8b3a2b76c2b3
Revises: ea3cfb3c4f19
Create Date: 2026-09-30 13:32:03.380232

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8b3a2b76c2b3"
down_revision: Union[str, Sequence[str], None] = "ea3cfb3c4f19"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###s
    with op.batch_alter_table("users") as batch_op:
        batch_op.add_column(
            sa.Column("encoded_playgroup_key", sa.String(length=240), nullable=True)
        )
    with op.batch_alter_table("guild_configs") as batch_op:
        batch_op.add_column(sa.Column("mtg_channel", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column("tracked_playgroup_id", sa.Integer(), nullable=True)
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users") as batch_op:
        batch_op.drop_column("encoded_playgroup_key")
    with op.batch_alter_table("guild_configs") as batch_op:
        batch_op.drop_column("tracked_playgroup_id")
        batch_op.drop_column("mtg_channel")
    # ### end Alembic commands ###
