"""add neko table

Revision ID: 8d7f4707df3e
Revises: 8f39a15793e4
Create Date: 2026-05-05 11:24:01.473443

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8d7f4707df3e"
down_revision: Union[str, Sequence[str], None] = "8f39a15793e4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nekos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("image_url", sa.String(length=400), nullable=False),
        sa.Column("nsfw", sa.Boolean(), nullable=True),
        sa.Column("rarity", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=400), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("image_url", name="uq_neko_image_url"),
    )
    op.create_index("ix_neko_rarity", "nekos", ["rarity"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_neko_rarity", table_name="nekos")
    op.drop_table("nekos")
    # ### end Alembic commands ###
