"""initial schema

Revision ID: 8f39a15793e4
Revises:
Create Date: 2026-05-05 03:22:42.541930

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8f39a15793e4"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("bingo_players", recreate="always") as batch_op:
        batch_op.create_unique_constraint(
            "uq_bingo_player_game_id_member_id", ["game_id", "member_id"]
        )

    with op.batch_alter_table("guild_configs", recreate="always") as batch_op:
        batch_op.create_unique_constraint("uq_guild_config_guild_id", ["guild_id"])
        batch_op.add_column(
            sa.Column(
                "enable_nsfw", sa.Boolean(), server_default=sa.text("0"), nullable=False
            )
        )

    with op.batch_alter_table("responses", recreate="always") as batch_op:
        batch_op.drop_constraint(op.f("uq_response_guild_trigger_text"), type_="unique")
        batch_op.create_unique_constraint(
            "uq_response_guild_trigger_text_exact",
            ["guild_id", "trigger", "text", "is_exact"],
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_response_guild_trigger_text_exact", "responses", type_="unique"
    )
    op.create_unique_constraint(
        op.f("uq_response_guild_trigger_text"),
        "responses",
        ["guild_id", "trigger", "text"],
    )
    op.drop_constraint("uq_guild_config_guild_id", "guild_configs", type_="unique")
    op.drop_column("guild_configs", "enable_nsfw")
    op.drop_constraint(
        "uq_bingo_player_game_id_member_id", "bingo_players", type_="unique"
    )
    op.drop_index("ix_bingo_game_guild_id", table_name="bingo_games")
    # ### end Alembic commands ###
