"""add_update_channel

Revision ID: b75e9c9ab3f5
Revises: 21b348e4408e
Create Date: 2026-05-10 12:43:50.916057

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "b75e9c9ab3f5"
down_revision: Union[str, Sequence[str], None] = "21b348e4408e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bingo_games", "known_entries")
    op.add_column(
        "guild_configs", sa.Column("update_channel", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("guild_configs", "update_channel")
    op.add_column(
        "bingo_games", sa.Column("known_entries", sqlite.JSON(), nullable=True)
    )
    # ### end Alembic commands ###
