"""remove_available_item

Revision ID: cad70a87a04f
Revises: 50482019320b
Create Date: 2026-05-14 00:41:40.346449

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cad70a87a04f"
down_revision: Union[str, Sequence[str], None] = "50482019320b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("train_items", "available")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("train_items", sa.Column("available", sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###
