"""fix_lazy_loads

Revision ID: d35e5fda2c90
Revises: 55a5f7403654
Create Date: 2026-05-06 18:18:20.196371

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d35e5fda2c90"
down_revision: Union[str, Sequence[str], None] = "55a5f7403654"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bingo_shots") as batch_op:
        batch_op.alter_column(
            "anilist_entry_id", existing_type=sa.INTEGER(), nullable=False
        )
        # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "bingo_shots", "anilist_entry_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
