"""gem_time_players

Revision ID: ea3cfb3c4f19
Revises: 73737f66f78e
Create Date: 2026-05-15 15:18:25.419294

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "ea3cfb3c4f19"
down_revision: Union[str, Sequence[str], None] = "73737f66f78e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
